### ISSUE TITLE
enhancement - Fiat conversion for respective countries 

### ISSUE THREAD

**Issue by hoodat432** [Nexusoft/Nexus-Interface-Invoice-Module#18]
Would it be possible to add fiat conversions for respective countries, perhaps US and AU for starters?  I've spoken to Paul about this briefly, there seems to be some complexities like where to pull accurate average price.  I can see this potential need for use cases we are working on.

**Comment by KenCorma** [comment]
Well we already have a fiat total at the bottom, this will take what ever fiat currency you have selected in the setting menu. Or are you looking to have the fiat at every item in the invoice?
