### ISSUE TITLE
Line Items don't get saved when saving Invoice as Draft

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/Nexus-Interface-Invoice-Module#25]
I filled out the top portion of the invoice, except for the reference.  Then I added invoice items with per unit amounts and unit amounts.  I then saved the invoice as a draft.  I immediately opened it back up and everything was fine.  I then added the reference, and saved it as draft again.  The reference didn't display on the table showing the draft invoice.  I then went to the transactions module of the wallet because I couldn't submit the invoice until so many confirmations had occurred on a recently staked block.  When the confirmations had occurred, I went back to the Invoice module and opened the draft invoice.  The reference and line item details were gone, as though they had never been entered.

**Comment by Qrysto** [comment]
@NealHelman Please confirm if this is fixed in v1.1.2

**Comment by NealHelman** [comment]
You fixed it!  Yay!
