### ISSUE TITLE
Invoice Total = NaN

### ISSUE THREAD

**Issue by Strikeh** [Nexusoft/Nexus-Interface-Invoice-Module#40]
Total price get's calculated as NaN resulting in the invoice not being sent/sumbitted

<img width="1104" alt="image" src="https://github.com/Nexusoft/nexus-invoice-module/assets/25606854/ce62e6a3-e773-4f42-96f4-e8d74d74428b">

In this example I set price to 1 and Quanty to 6600 -> Total is NaN

**Comment by Qrysto** [comment]
Isn't price blank in this screenshot?

**Comment by Strikeh** [comment]
in the screenshot it is, but it's not what I filled in, this is after the invoice was sent I believe

**Comment by Qrysto** [comment]
@Strikeh What's the exact steps to reproduce this issue? I tried entering those inputs and the Total was displayed correctly

**Comment by Strikeh** [comment]
> @Strikeh What's the exact steps to reproduce this issue? I tried entering those inputs and the Total was displayed correctly

I'll check it out later today, I'll let you know whether or not it still occurs
